theme: jekyll-theme-minimal
title: "List of R tools for microbiome data analysis"

twitter: 'gutmicrobe'
github:
  repository_url: https://github.com/microsud/Tools-Microbiome-Analysis  


# Admin Settings
admin_name: 'Sudarshan_Shetty'
admin_email: 'sudarshanshetty9@gmail.com'

# Site Author
author:
  name             : "Sudarshan A. Shetty"  
  

